### ISSUE TITLE
Issue with refresh rate reverting

### ISSUE THREAD

**Issue by tscan89** [Nonary/MonitorSwapAutomation#19]
I set this up in conjunction with the ResolutionAutomation and installed per instructions. I am using MonitorSwapAutomation and ResolutionAutomation to swap to a [Virtual Display Adapter](https://github.com/itsmikethetech/Virtual-Display-Driver) (instead of a dummy plug), disconnect my physical displays, activate my virtual display adapter, and change the resolution/refresh rate on my virtual display adapter to match the streaming resolution set by the Moonlight client. The issue that I'm having is that the refresh rate of the Virtual Display Adapter seems to revert back to whatever the `DisplayFrequency` is in dummy.cfg whenever I hop in a game. If I open a Desktop stream on a Moonlight client with the display adapter properties open on the Virtual Display Adapter, it appears that the resolution and refresh rate are set correctly, but as soon as I hop in a game the refresh rate seems to revert. I tested this by rebooting my PC, setting the `DisplayFrequency` to a different value in dummy.cfg, and starting the game. Sure enough, the monitor refresh rate stayed at whatever value I set in `DisplayFrequency`. I wouldn't be able to tell if the bug is in this tool or in ResolutionAutomation, but there is something funky going on somewhere.

**Comment by Nonary** [comment]
This should be fixed in the latest release of the ResolutionAutomation script. 

Basically due to timing issues sometimes the swap could happen before or after the resolution changes,  causing inconsistent behavior.

The changes made in latest release address this issue by continuing to change resolution for up to 6 seconds afterwards if it doesn't match again.
