### ISSUE TITLE
I want to put my PC into sleep after disconnecting streaming, how to do with this script?

### ISSUE THREAD

**Issue by twilightgod** [Nonary/MonitorSwapAutomation#51]

**Comment by Nonary** [comment]
You can add this line of code to the OnStreamEnd function in Events


```powershell
& rundll32.exe powrprof.dll, SetSuspendState Sleep
```

**Comment by twilightgod** [comment]
I see there are many places OnStreamEnd will return true of false, which path should I add this line of code? If I sleep here, will it impact the execution of the rest of the code?
Or I should add it in the caller such as Wait-ForStreamEndJobToComplete?

**Comment by Nonary** [comment]
> I see there are many places OnStreamEnd will return true of false, which path should I add this line of code? If I sleep here, will it impact the execution of the rest of the code? Or I should add it in the caller such as Wait-ForStreamEndJobToComplete?

In your case the best area to place it is right after the try statement, because you want the PC to go to sleep immediately. Once it wakes up, the code picks up right after that and works as normal (the restoring of the screen) nothing else has to be changed. On the code editors that would be like 68 or 69 to you

**Comment by Edenleuf** [comment]
Just a heads up if anyone had issues with this like i did, adding the command does work but for newer versions of windows it apparently puts your pc into hibernate instead of sleep if you have hibernate enabled. This wouldn't normally be an issue for me but it also makes it so wake on lan requests won't work.

But diabling hibernation solves this as per https://superuser.com/a/42128

**Comment by twilightgod** [comment]
Thanks, it works for me, but I'm thinking about there should be a config or another PowerShell file that users can put their customized command before and after the monitor swap code runs.

**Comment by twilightgod** [comment]
I found the better place to do sleep is in sunshine web UI config, I can set do and undo command.
I added sleep command after this script, it works great, I don't need to change any code then.
